### ISSUE TITLE
Initializing Connext

### ISSUE THREAD

**Issue by Gr8z** [oslabs-beta/connext-js#10]
Where does this piece of code go in my nextjs app? I don't have an index.js file or the sorts, I just have pages and component directories.

```js
const Connext = require('connext-js');
const app = Connext();
```

**Comment by Gr8z** [comment]
Oh, I am an idiot, this should go on each individual routes

**Comment by Gr8z** [comment]
Oh no, these go on pages/api/route.js files

Can you guide me to the right direction?

**Comment by akang0408** [comment]
In your Next.js application an API route is created each time you create a javascript file inside of the required 'api' folder. This api folder must be a folder created inside of the 'pages' folder that Next.js requires you to create to use their built in routing system. Simply add the snippet of code you posted at the top of any '.js' file inside of your 'api' folder and you can proceed to follow the docs on setting up different routes within that file.

To utilize Connext's global middleware functionality, you must create a global.js file in a folder called controllers. The controllers folder must be at the same level as your pages folder and your global.js file must export an array.
