### ISSUE TITLE
Cannot find module dirext-js/index.js

### ISSUE THREAD

**Issue by zhicong** [oslabs-beta/connext-js#12]
Thanks for creating this, this is exactly what I was looking for in Next.js! I'm getting an error when I try to hit an API route after installing Connext though:

> Error: Cannot find module '< app path >/node_modules/dirext-js/index.js'. Please verify that the package.json has a valid "main" entry
>     at tryPackage (internal/modules/cjs/loader.js:316:19)
>     at Function.Module._findPath (internal/modules/cjs/loader.js:705:18)
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:969:27)
>     at Function.Module._load (internal/modules/cjs/loader.js:864:27)
>     at Module.require (internal/modules/cjs/loader.js:1044:19)
>     at require (internal/modules/cjs/helpers.js:77:18)
>     at Object.<anonymous> (< app path >/node_modules/connext-js/lib/index.js:44:14)
>     at Module._compile (internal/modules/cjs/loader.js:1158:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
>     at Module.load (internal/modules/cjs/loader.js:1002:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:901:14)
>     at Module.require (internal/modules/cjs/loader.js:1044:19)
>     at require (internal/modules/cjs/helpers.js:77:18)
>     at Object.connext-js (< app path >/.next/server/static/development/pages/api/hotels-list.js:280:18)
>     at __webpack_require__ (< app path >/.next/server/static/development/pages/api/hotels-list.js:23:31)
>     at Module../pages/api/apiRoute.js (< app path >/.next/server/static/development/pages/api/hotels-list.js:247:68) {
>   code: 'MODULE_NOT_FOUND',
>   path: '< app path >/node_modules/dirext-js/package.json',
>   requestPath: 'dirext-js'
> }
>

**Comment by sarapowers** [comment]
Hi! It was an issue with our file path in our routing package, we've updated it and it should be working now. Thanks so much for using Connext!
